sticky:
  id: sticky
  table: node_field_data
  field: sticky
  relationship: none
  group_type: group
  admin_label: ''
  entity_type: node
  entity_field: sticky
  plugin_id: standard
  order: ASC
  expose:
    label: ''
    field_identifier: ''
  exposed: false
