<?php

/**
 * @file
 * Satellite Core module file.
 */

use Drupal\Core\File\FileExists;

/**
 * Implements hook_modules_installed().
 */
function satellite_core_modules_installed($modules, $is_syncing) {
  if (in_array('satellite', $modules)) {
    if (empty(\Drupal::entityTypeManager()->getStorage('media')->loadByProperties(['uuid' => '9916b40b-d139-4866-b350-599bf75479f4']))) {
      // Add media esnstar for default image.
      $theme_path = \Drupal::service('extension.list.theme')->getPath('satellite_theme');

      $image_data = file_get_contents("$theme_path/ESNstar_digital_full_colour.png");
      $file_repository = \Drupal::service('file.repository');
      $image = $file_repository->writeData($image_data, "public://esnstar.png", FileExists::Replace);

      $image_media = \Drupal::entityTypeManager()->getStorage('media')->create([
        'uuid' => '9916b40b-d139-4866-b350-599bf75479f4',
        'name' => 'ESN Star',
        'bundle' => 'image',
        'uid' => 1,
        'langcode' => 'en',
        'status' => 1,
        'field_media_image' => [
          'target_id' => $image->id(),
          'alt' => t('Logo of ESN. Colorful star'),
        ],
      ]);
      $image_media->save();
    }
  }
}
